import type { Metadata } from "next";

import { Provider } from "@/components/ui/provider"
import Navbar from "@/design-system/components/Navbar";
import CopyRights from "@/design-system/components/CopyRights";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Provider>
      <Navbar/>
        {children}
        <CopyRights/>
        </Provider>
      </body>
    </html>
  );
}
